version: "3"

services:
  traefik:
    image: "traefik:v3.1.2"
    logging:
      driver: local
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./letsencrypt:/letsencrypt:rw"

  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`api.anasdidi.dev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    networks:
      - traefik-network
    logging:
      driver: local

networks:
  traefik-network:
    name: traefik-network
