version: "3"

services:
  traefik-docker:
    image: traefik:v3.2
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=anas:$$2y$$05$$OX/Kgw6dTLZw.6GtQh2m8.sdXuRM5RW6dWfgvEgVwFgJxzUKSDcjS"
    command:
      - "--entryPoints.web.address=:80"
      #- "--entryPoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker"
    logging:
      driver: local
    networks:
      - anas-didi95-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`localhost`) && PathPrefix(`/whoami`)"
    logging:
      driver: local
    networks:
      - anas-didi95-network

networks:
  anas-didi95-network:
    external:
      name: anas-didi95-network
