log:
  level: DEBUG

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: {}
      email: anas.didi95@gmail.com
      storage: /letsencrypt/acme.json
