version: "3"

services:
  edumgmt-server:
    image: ghcr.io/anas-didi95/edumgmt-server-micronaut:dev
    command:
      - "-Xms64m"
      - "-Xmx128m"
    logging:
      driver: local
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edumgmt-server.rule=Host(`localhost`) && PathPrefix(`/edumgmt`)"
      - "traefik.http.routers.edumgmt-server.entrypoints=web"
    env_file:
      - .env
    volumes:
      - "./h2:/edumgmt/.h2:rw"

networks:
  traefik-network:
    external:
      name: traefik-network
