version: "3"

services:
  edumgmt-server:
    image: ghcr.io/anas-didi95/edumgmt-server-micronaut:dev
    command:
      - "-Xms128m"
      - "-Xmx256m"
    logging:
      driver: local
    networks:
      - anas-didi95-network
    env_file:
      - "~/anas-didi95-env/edumgmt-server.env"
    volumes:
      - "./h2/:/edumgmt/h2/:rw"

networks:
  anas-didi95-network:
    external:
      name: anas-didi95-network
