version: "3"

services:
  edumgmt-server:
    image: ghcr.io/anas-didi95/edumgmt-server-micronaut:dev
    command:
      - "-Xms64m"
      - "-Xmx128m"
    logging:
      driver: local
    networks:
      - edumgmt-server
    env_file:
      - ".env"

networks:
  edumgmt-server:
    name: edumgmt-server
