---
networks:
  anas-didi95-network:
    external: true
services:
  app-portal:
    env_file:
      - ".env"
    image: "ghcr.io/anas-didi95/anas-didi95-portal:develop"
    labels:
      - "traefik.http.routers.portal.rule=Host(`localhost`) && PathPrefix(`/portal/`)"
    logging:
      driver: "local"
    networks:
      - "anas-didi95-network"
    volumes:
      - "./h2/:/home/app/h2/:z"
